### ISSUE TITLE
mex umbiguity

### ISSUE THREAD

**Issue by antiquity** [stephenbeckr/L-BFGS-B-C#1]
For linux system with latex system installed, the `mex` can be taken as  a command for `pdftex`.  I think it is better to add the following to the beginning of `Makefile`:

```
MATLAB = $(shell matlab -e | sed -n 's/MATLAB=//p')
CC = $(MATLAB)/bin/mex
```

**Comment by stephenbeckr** [comment]
Good idea. I've updated to include the new version you suggest.
