### ISSUE TITLE
L BFGS B fortran to matlab code conversion

### ISSUE THREAD

**Issue by Dinah14** [stephenbeckr/L-BFGS-B-C#10]
can you please help me convert l bfgs b fortran code to matlab code.

**Comment by stephenbeckr** [comment]
Sorry, I don't have time to help with converting your code. Could you keep it in Fortran and call a Fortran version of L-BFGS-B?

**Comment by Dinah14** [comment]
I just want the MATLAB version of LBFGS B fortran. Can you help me ? I am willing to pay

**Comment by stephenbeckr** [comment]
It sounds like you want the "MATLAB version of LBFGS B fortran". This code repository is an equivalent C version of L-BFGS-B, with mex-code wrapper that let's you use it from MATLAB. So is that what you want?  I'm going to close out this issue.

**Comment by Dinah14** [comment]
Yes
