### ISSUE TITLE
-lm option should be put in the end of the gcc command

### ISSUE THREAD

**Issue by antiquity** [stephenbeckr/L-BFGS-B-C#2]
Dear, Dr. Becker,

I have some problem in compiling the code under `src` directory.  It warns me by

```
undefined reference to `sqrt'
```

It should be the problem of linking with math library. Although `CFLAG` has this option, it is not at the end of the `gcc` command, which causes problem here in linux.

**Comment by stephenbeckr** [comment]
Thanks for noticing. I adjusted the Makefile in `src` to put `-lm` at the end of the line. Please let me know if this fixes the issue for you.

**Comment by antiquity** [comment]
Thanks. That fixed my problem.
