### ISSUE TITLE
CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL 

### ISSUE THREAD

**Issue by xilinnancheng** [stephenbeckr/L-BFGS-B-C#7]
Hello,I have come across an issue when I set the lower bounds(-0.2) and upper bounds(0.2) in my project [cubic_spiral](https://github.com/xilinnancheng/cubic_spiral).
The debugging info:
`lbfgs_message1 = CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL.` and iteration_cnt = 1.
It seems that it doesn't start to find the solution. However, it works well if I set the lower bounds(-inf) and upper bounds(-inf).
Thanks.

**Comment by stephenbeckr** [comment]
I'm not sure this is a bug in the code. It could mean that it thinks the initial point is an acceptable enough solution. If it's not acceptable, try reducing `pgtol`

**Comment by xilinnancheng** [comment]
Thanks, I'll try it.
